(function(){
  const user = JSON.parse(localStorage.getItem('user') || 'null');
  const apiBase = (window.CONFIG && CONFIG.PROFILE_API_BASE ? CONFIG.PROFILE_API_BASE : '').replace(/\/$/, '');
  const els = {
    loginBtn: document.getElementById('loginProfileBtn'), displayName: document.getElementById('profileDisplayName'), discordId: document.getElementById('profileDiscordId'), countBadge: document.getElementById('profileCountBadge'), avatar: document.getElementById('profileAvatar'), dangerStatus: document.getElementById('profileDangerStatus'), charsCount: document.getElementById('profileCharactersCount'), playtime: document.getElementById('profilePlaytime'), apiNote: document.getElementById('profileApiNote'), message: document.getElementById('profileMessage'), grid: document.getElementById('charactersGrid'), detailsSection: document.getElementById('profileDetailsSection'), detailFullnameTitle: document.getElementById('detailFullnameTitle'), detailCitizenId: document.getElementById('detailCitizenId'), detailJobBadge: document.getElementById('detailJobBadge'), detailGangBadge: document.getElementById('detailGangBadge'), detailDutyBadge: document.getElementById('detailDutyBadge'), detailCharacterImage: document.getElementById('detailCharacterImage'), detailFullname: document.getElementById('detailFullname'), detailBirthdate: document.getElementById('detailBirthdate'), detailPhone: document.getElementById('detailPhone'), detailNationality: document.getElementById('detailNationality'), detailGender: document.getElementById('detailGender'), detailAccount: document.getElementById('detailAccount'), detailCash: document.getElementById('detailCash'), detailBank: document.getElementById('detailBank'), detailCrypto: document.getElementById('detailCrypto'), detailSalary: document.getElementById('detailSalary'), vehiclesList: document.getElementById('vehiclesList'), housesList: document.getElementById('housesList'), skillsList: document.getElementById('skillsList'), inventoryList: document.getElementById('inventoryList')
  };
  let loadedCharacters = [];
  function money(v){ return `$${Number(v || 0).toLocaleString()}`; }
  function avatarFallback(name){ const safe = encodeURIComponent(name || 'Character'); return `https://ui-avatars.com/api/?name=${safe}&background=111111&color=ffffff&size=256`; }
  if(!user){ window.location.href = 'login.html'; return; }
  els.displayName.textContent = user.global_name || user.name || user.username || 'Unknown';
  els.discordId.textContent = `Discord ID: ${user.id || '-'}`;
  els.avatar.src = user.avatar || avatarFallback(user.name || user.username || 'User');
  els.loginBtn.textContent = 'تسجيل الخروج';
  els.loginBtn.href = '#';
  els.loginBtn.onclick = function(e){ e.preventDefault(); localStorage.removeItem('user'); localStorage.removeItem('plusdev_user'); window.location.href = 'index.html'; };
  function renderCharacterCard(char, index){ return `<article class="character-card"><div class="character-card-top"><div><h3>${char.fullname || 'Unnamed Character'}</h3><div class="character-sub">${char.job || 'Civilian'}${char.grade ? ` • ${char.grade}` : ''}</div></div><img class="character-avatar" src="${char.image || avatarFallback(char.fullname)}" alt="character" /></div><div class="character-money-grid"><div><div class="muted">نقد</div><div class="character-money-value green">${money(char.cash)}</div></div><div><div class="muted">بنك</div><div class="character-money-value blue">${money(char.bank)}</div></div><div><div class="muted">عملات رقمية</div><div class="character-money-value purple">${money(char.crypto)}</div></div></div><div class="character-actions"><div class="profile-badges"><span class="profile-badge soft">${char.gang || 'No Gang Affiliation'}</span><span class="profile-badge soft">${char.onduty ? 'في الخدمة' : 'خارج الخدمة'}</span></div><button class="show-details-btn" data-index="${index}">عرض التفاصيل</button></div></article>`; }
  function fillCharacterDetails(char){ els.detailsSection.classList.remove('hidden'); els.detailFullnameTitle.textContent = char.fullname || '-'; els.detailCitizenId.textContent = char.citizenid || '-'; els.detailJobBadge.textContent = char.job || 'Civilian'; els.detailGangBadge.textContent = char.gang || 'No Gang Affiliation'; els.detailDutyBadge.textContent = char.onduty ? 'في الخدمة' : 'خارج الخدمة'; els.detailCharacterImage.src = char.image || avatarFallback(char.fullname); els.detailFullname.textContent = char.fullname || '-'; els.detailBirthdate.textContent = char.birthdate || '-'; els.detailPhone.textContent = char.phone || '-'; els.detailNationality.textContent = char.nationality || '-'; els.detailGender.textContent = char.gender || '-'; els.detailAccount.textContent = char.account || '-'; els.detailCash.textContent = money(char.cash); els.detailBank.textContent = money(char.bank); els.detailCrypto.textContent = money(char.crypto); els.detailSalary.textContent = money(char.salary); }
  function renderAssets(listEl, items, mapper){ if(!items || !items.length){ listEl.innerHTML = '<div class="profile-message small">لا توجد بيانات</div>'; return; } listEl.innerHTML = items.map(mapper).join(''); }
  async function loadAssets(citizenid){ if(!apiBase){ els.vehiclesList.innerHTML = '<div class="profile-message small">أضف رابط API أولًا داخل config.js</div>'; els.housesList.innerHTML = '<div class="profile-message small">أضف رابط API أولًا داخل config.js</div>'; els.skillsList.innerHTML = '<div class="profile-message small">أضف رابط API أولًا داخل config.js</div>'; els.inventoryList.innerHTML = '<div class="profile-message small">أضف رابط API أولًا داخل config.js</div>'; return; } try{ const [assetsRes, extraRes] = await Promise.all([ fetch(`${apiBase}/api/me/assets/${encodeURIComponent(citizenid)}`), fetch(`${apiBase}/api/me/extra/${encodeURIComponent(citizenid)}`) ]); const assetsData = await assetsRes.json().catch(()=>({})); const extraData = await extraRes.json().catch(()=>({})); renderAssets(els.vehiclesList, assetsData.vehicles || [], (vehicle) => `<div class="asset-card"><div><div class="asset-title">${vehicle.model || 'Unknown Vehicle'}</div><div class="asset-sub">${vehicle.plate || '-'}</div></div><div class="asset-meta"><span>${vehicle.garage || 'Unknown'}</span><span class="asset-state">${vehicle.state ?? '-'}</span></div></div>`); renderAssets(els.housesList, assetsData.houses || [], (house) => `<div class="asset-card"><div><div class="asset-title">${house.name || 'Unknown House'}</div><div class="asset-sub">${house.type || 'Owned'}</div></div></div>`); renderAssets(els.skillsList, extraData.skills || [], (skill) => { const width = Math.min((Number(skill.level || 0) * 18), 100); return `<div class="skill-card"><div class="skill-head"><div class="skill-name">${skill.name || 'Unknown'}</div><div class="skill-level">Lv ${Number(skill.level || 0)}</div></div><div class="skill-bar"><div class="skill-fill" style="width:${width}%"></div></div></div>`; }); renderAssets(els.inventoryList, extraData.items || [], (item) => `<div class="inventory-item"><div class="inventory-count">x${Number(item.amount || 1)}</div><div class="inventory-name">${item.label || item.name || 'Unknown Item'}</div><div class="inventory-meta">${item.type || 'item'}</div></div>`); }catch(err){ els.vehiclesList.innerHTML = '<div class="profile-message small">فشل تحميل المركبات</div>'; els.housesList.innerHTML = '<div class="profile-message small">فشل تحميل العقارات</div>'; els.skillsList.innerHTML = '<div class="profile-message small">فشل تحميل المهارات</div>'; els.inventoryList.innerHTML = '<div class="profile-message small">فشل تحميل المخزون</div>'; } }
  async function showDetails(index){ const char = loadedCharacters[index]; if(!char) return; fillCharacterDetails(char); await loadAssets(char.citizenid); }
  async function loadCharacters(){ if(!apiBase){ els.apiNote.classList.remove('hidden'); els.message.textContent = 'الواجهة جاهزة. ضع رابط API داخل config.js في المفتاح PROFILE_API_BASE.'; return; } els.apiNote.classList.add('hidden'); try{ const response = await fetch(`${apiBase}/api/me/characters?discordId=${encodeURIComponent(user.id || '')}`); const data = await response.json(); if(!response.ok){ els.message.textContent = data.error || 'فشل تحميل الشخصيات'; return; } loadedCharacters = data.characters || []; if(!loadedCharacters.length){ els.message.textContent = 'لا توجد شخصيات مرتبطة بهذا الحساب'; return; } els.message.classList.add('hidden'); els.grid.innerHTML = loadedCharacters.map((char, idx) => renderCharacterCard(char, idx)).join(''); els.grid.querySelectorAll('.show-details-btn').forEach(btn => btn.addEventListener('click', ()=>showDetails(Number(btn.dataset.index)))); els.charsCount.textContent = String(data.count || loadedCharacters.length); els.countBadge.textContent = `${data.count || loadedCharacters.length} شخصية`; const first = loadedCharacters[0]; els.dangerStatus.textContent = first.dangerStatus || 'نظيف'; els.dangerStatus.className = `profile-stat-value ${(first.dangerStatus === 'مطلوب') ? 'red' : 'green'}`; els.playtime.textContent = first.playtime || '0h 0m'; showDetails(0); }catch(err){ els.message.textContent = 'فشل الاتصال بواجهة البيانات'; } }
  loadCharacters();
})();
